from = "top"

[input]
directory = "/root/voxel/ozark_slices/wb_va"

[output]
directory = "/root/voxel/ozark_slices/wb_vaw"
set_color = [0, 0, 0, 0]
# replace_color = [247, 247, 247, 128]
replace_color = [255, 255, 255, 255]